name: Deploy Portfolio Online
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy
        uses: actions/checkout@v3
        with: 
          fetch-depth: 2
      - name: Sync Folders and files to the server 
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./.output/public/
      
  
